### ISSUE TITLE
Upgrade kernel package

### ISSUE THREAD

**Issue by babbarc** [theSkele/arch-jetson-nano#5]
How to upgrade kernel package?

**Comment by hungpham3112** [comment]
@theSkele Hi, thank to your `autobuild-arch-nano.sh` I can easily install arch linux on my jetson nano. After logging in the system for the first time, I updated with `pacman -Syu `  and stumbled upon `/bin/sh: symbol lookup error: /usr/lib/libc.so.5: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE`. I am not Arch Linux expert, so can you help me to understand this problem?

**Comment by theSkele** [comment]
Please refer to [NVIDIA L4T Kernel Customization](https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3275/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/kernel_custom.html#) and [Arch Wiki - Kernel Compilation](https://wiki.archlinux.org/title/Kernel/Traditional_compilation)

NVIDIA provides a Linux version 4.9 based kernel (tegra-4.9), I am unsure what the consequences are if you chose a newer version.

You may also find this useful [OE4T/linux-tegra-4.9](https://github.com/OE4T/linux-tegra-4.9)

**Comment by theSkele** [comment]
> @theSkele Hi, thank to your `autobuild-arch-nano.sh` I can easily install arch linux on my jetson nano. After logging in the system for the first time, I updated with `pacman -Syu ` and stumbled upon `/bin/sh: symbol lookup error: /usr/lib/libc.so.5: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE`. I am not Arch Linux expert, so can you help me to understand this problem?

Not sure what would cause that, libc.so.5 is very very old and shouldnt even be used. Possibly try upgrading glibc?
